# Generated by Django 3.1.2 on 2021-03-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0008_auto_20210311_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='image',
            field=models.ImageField(default='thumb-1920-1073527.png', upload_to='Images/'),
        ),
    ]
